import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nevbar from "@/component/Nevbar";
import Footer from "@/component/Footer";
import { WixClientContextProvider } from "@/context/wixContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "eCOM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <WixClientContextProvider>
        <Nevbar/>
        {children}
        <Footer/>
      </WixClientContextProvider>

      </body>
    </html>
  );
}
